.executor-shell: &executor-shell
    tags:
        - shell

.nvm-use: &nvm-use
    before_script:
        - nvm use

.dependency-build: &dependency-build
    dependencies:
        - build

.only-branches: &only-branches
    except:
        - master
        - develop
        - tags
        - triggers

.not-branches: &not-branches
    only:
        - master
        - develop
        - tags

stages:
    - setup
    - build
    - compliance
    - accessibility-tests
    # Once src is added uncomment this stage to push the docker image to a registry
    # - push

nvm:
    stage: setup
    <<: *executor-shell
    script:
        - nvm install

conventional-changelog-lint-branch:
    stage: compliance
    <<: *executor-shell
    <<: *nvm-use
    <<: *dependency-build
    script:
        - git fetch origin develop --quiet
        - git checkout develop --quiet && git reset --hard origin/develop --quiet && git checkout - --quiet
        - npm run compliance:conventional-changelog-lint
    <<: *only-branches

conventional-changelog-lint:
    stage: compliance
    <<: *executor-shell
    <<: *nvm-use
    <<: *dependency-build
    script:
        - git fetch origin master --quiet
        - git checkout master --quiet && git reset --hard origin/master --quiet && git checkout - --quiet
        - ./node_modules/.bin/conventional-changelog-lint --from=master --to=develop
    only:
        - develop
build:
    stage: build
    script:
        - npm install
    <<: *not-branches

aXe:
    stage: accessibility-tests
    <<: *executor-shell
    <<: *nvm-use
    <<: *dependency-build
    script:
        - docker run --network="host" $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
        - docker build --build-arg BUILD_TOKEN=$CI_JOB_TOKEN -f Dockerfile -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME .
    <<: *not-branches
    allow_failure: false
# Once src is added uncomment this stage to push the docker image to a registry
# push:
#     stage: push
#     script:
#         - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#         - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
#     <<: *not-branches
